### ISSUE TITLE
Check out tf.contrib.Dataset if it's worth the effort

### ISSUE THREAD

**Issue by oskopek** [oskopek/ml_project_template#5]

**Comment by jendelel** [comment]
It seems like a nice and reasonable way on how to load data. Let's keep it in mind and add it later if necessary. Nice blog post:
https://kratzert.github.io/2017/06/15/example-of-tensorflows-new-input-pipeline.html and its follow-up:
https://kratzert.github.io/2017/09/11/speeding-up-tensorflows-input-pipeline.html

Code:
https://github.com/kratzert/finetune_alexnet_with_tensorflow/blob/master/datagenerator.py
https://github.com/kratzert/finetune_alexnet_with_tensorflow/blob/master/finetune.py
