### ISSUE TITLE
Test Lukas' environment

### ISSUE THREAD

**Issue by oskopek** [oskopek/ml_project_template#7]
* [ ] Test in Lukas' environment
* [ ] Test colab notebook sharing
* [ ] Review for workflow

**Comment by jendelel** [comment]
Docker doesn't work on my PC. It requires Win Pro.

**Comment by oskopek** [comment]
Shouldn't matter too much, you don't need it for local execution. This will become apparent in the new README, hopefully. Did you try setting up the environment/using it, and running shared colab notebooks?

**Comment by oskopek** [comment]
Fixed virtualenv check, colab works fine.
